spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedextracker
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
#  sql:
#    init:
#      data-locations: classpath:data/intellij/

api:
  jwt:
    secret: GE4AxDKB$NA!dEb4hoiyiC!Dh*825UC*ArRH